cstorm2/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^round2/', include('round2.urls')),
]

round2/urls.py
from django.conf.urls import url
from . import views

app_name = 'round2'

urlpatterns = [
    # /round2/question/(user_id)
    url(r'^question/(?P<user_id>[0-9]+)/$', views.question, name="question"),
    url(r'^add_que/(?P<user_id>[0-9]+)/$', views.add_que, name="add_que"),
    #/round2/login)
    url(r'^register/$', views.register, name="register"),
    #/round2/login/create_user
    url(r'^login/create_user/$', views.create_user, name="create_user"),
    # /round2/user_id/(question_id)
    url(r'^(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question_details, name='question_details'),
    # /round2/question/(user_id)/(question_id)
    url(r'^(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/next/$', views.handle_answer, name='handle_answer'),
    url(r'^buy_question/(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.buy_question, name='buy_question'),
    url(r'^leaderboard/(?P<user_id>[0-9]+)/$', views.leaderboard, name='leaderboard'),
    url(r'^instruction_view/(?P<user_id>[0-9]+)/$', views.instruction_view, name='instruction_view'),

]

round2/models.py
from django.db import models


class User(models.Model):
    login_name = models.CharField(max_length=100)
    phone_number1 = models.IntegerField()
    phone_number2 = models.IntegerField()
    college_name1 = models.CharField(max_length=100)
    college_name2 = models.CharField(max_length=100)
    user_name1 = models.CharField(max_length=100)
    user_name2 = models.CharField(max_length=100)
    email1 = models.CharField(max_length=100)
    email2 = models.CharField(max_length=100)
    total_score = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    # score = models.TextField()
    money = models.IntegerField(default=100)
    easy_counter = models.IntegerField(default=0)

    def __str__(self):
        return str(self.pk)


class Question(models.Model):
    question = models.TextField(max_length=4000)
    question_title = models.CharField(max_length=2000)
    input = models.CharField(default=0, max_length=5000)
    correct_op = models.CharField(default=0, max_length=10000)
    explanation = models.CharField(max_length=7000)
    test_input = models.CharField(max_length=100000)
    test_output = models.CharField(max_length=10000)
    cost = models.IntegerField()
    user = models.ManyToManyField(User, null=True, through="Score")
    type = models.CharField(default="Easy", max_length=10)

    def __str__(self):
        return self.question_title


class Score(models.Model):
    user_f = models.ForeignKey(User, on_delete=models.CASCADE)
    question_f = models.ForeignKey(Question, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

round2/views.py
import os
import signal

from django.shortcuts import render, HttpResponse
from .models import User, Question, Score
import subprocess
import json
import pyperclip
from subprocess import Popen, PIPE
import time
import threading

# import signal, sys

time_finish = True
ps_id = 0
tle = False


def timeout(sig, frm):
    print('timeout')
    # time_finish = True
    if time_finish == True:
        print("Finished")
        os.killpg(os.getpgid(ps_id), signal.SIGTERM)
        tle = True
        return HttpResponse("TLE")
        # raise Exception


signal.signal(signal.SIGALRM, timeout)


def question(request, user_id):
    all_questions = Question.objects.all()
    current_user = User.objects.get(pk=user_id)
    jsonDec = json.decoder.JSONDecoder()
    # all_marks = list(jsonDec.decode(current_user. score))
    current_user.total_score = 0
    temp = 0
    # for marks in all_marks:
    #     temp += marks
    question_list = []
    for questions in all_questions:
        if current_user in questions.user.all():
            question_list.append({"question": questions,
                                  "status": "bought",
                                  "cost": questions.cost,
                                  "difficulty": questions.type,
                                  "question_score": Score.objects.get(user_f=current_user, question_f=questions).score})
        else:
            question_list.append({"question": questions,
                                  "status": "not bought",
                                  "cost": questions.cost,
                                  "difficulty": questions.type,
                                  "question_score": 0
                                  })

    current_user.total_score = temp
    current_user.save()
    print(current_user.total_score)

    # return render(request, 'round2/questions_list.html', {'all_questions' : all_questions, 'user_id': user_id,'remaining_time':current_user.end_time-time.time(),'all_marks':all_marks ,'one':50,'two':50,'three':100,'four':100})
    return render(request, 'round2/select_questions_new.html',
                  {'buyed_questions': '', 'all_questions': all_questions, 'user_id': user_id,
                   'remaining_time': current_user.end_time - time.time(), 'question_list': question_list,
                   'money': current_user.money})


def register(request):
    return render(request, 'round2/register_new.html', {})


def create_user(request):
    team_name = request.POST.get('team_name')
    participant1 = request.POST.get('participant1')
    mobile1 = request.POST.get('mobile1')
    college1 = request.POST.get('college1')
    email1 = request.POST.get('email1')
    reciept_number = request.POST.get('reciept_number')
    participant2 = request.POST.get('participant2')
    mobile2 = request.POST.get('mobile2')
    college2 = request.POST.get('college2')
    email2 = request.POST.get('email2')
    msg = ''

    new_user = User(login_name=team_name, phone_number1=mobile1, phone_number2=mobile2,
                    college_name1=college1,
                    college_name2=college2, user_name1=participant1, user_name2=participant2, email1=email1,
                    email2=email2, end_time=(time.time() + (60 * 120)))
    print(new_user.end_time)
    new_user.save()
    # return question(request,new_user.pk)
    return instruction_view(request, new_user.pk)


def question_details(request, user_id, question_id):
    selected_question = Question.objects.get(pk=question_id)
    print(selected_question)
    current_user = User.objects.get(pk=user_id)
    print(current_user.end_time)
    print(current_user.end_time - time.time())
    bought = False
    if current_user in selected_question.user.all():
        bought = True

    jsonDec = json.decoder.JSONDecoder()
    current_user.total_score = 0
    # all_marks = list(jsonDec.decode(current_user.score))
    # for marks in all_marks:
    #     current_user.total_score += marks
    current_user.save()
    try:
        previous_code = open(str(question_id) + '_' + str(user_id) + '.cpp', 'r').read()
    except:
        previous_code = ""
    return render(request, 'round2/question_details.html',
                  {'pegs_id': int("3"), 'bought': bought, 'selected_question': selected_question,
                   'question_id': selected_question.pk,
                   'user_id': user_id, 'submitted_code': previous_code,
                   'remaining_time': current_user.end_time - time.time(),
                   'money': current_user.money})


def handle_answer(request, user_id, question_id):
    if request.POST.get("finish"):
        return leaderboard(request, user_id)
    # code = request.POST.get("text_area")
    if request.POST.get("submit"):
        code = request.POST.get("text_area")

        # print(code)
        f = open(str(question_id) + '_' + str(user_id) + '.cpp', 'w')

        # f=open('test.cpp','w')
        f.write(code)

        f.close()

        print("printing my code")
        # print(code)
        current_question = Question.objects.get(pk=question_id)
        jsonDec = json.decoder.JSONDecoder()
        correct_op = list(jsonDec.decode(current_question.correct_op))
        input = list(jsonDec.decode(current_question.input))
        '''pyperclip.copy('The text to be copied to the clipboard.')
            return render(request, 'round2/question_details.html',
                      {'submitted': True, 'submitted_code': str(code), 'selected_question': current_question,
                       'user_id': user_id})'''
        t = 0
        # from subprocess import CalledProcessError, check_output
        compile_ouput = subprocess.getoutput(
            'g++ ' + str(question_id) + '_' + str(user_id) + '.cpp -o ' + str(question_id) + '_' + str(
                user_id) + '.out')
        marks = 0
        current_user = User.objects.get(pk=user_id)
        # Successfully complied
        if not compile_ouput:
            print('compiled')
            '''f = open('output.txt', 'w')
                        output = subprocess.check_output('a.exe', universal_newlines=True, shell=True)
                        f.write(output)
                        f.close()'''

            input_length = len(input)
            counter = 0
            result = [None] * len(input)
            checker = [None] * len(input)
            try:
                for ii in input:

                    p = Popen(['./' + str(question_id) + '_' + str(user_id) + '.out'], shell=True, stdout=PIPE,
                              stdin=PIPE,
                              preexec_fn=os.setsid)
                    value = str(ii) + '\n'
                    value = bytes(value, 'UTF-8')  # Needed in Python 3.

                    p.stdin.write(value)
                    p.stdin.flush()
                    global time_finish
                    time_finish = True
                    global ps_id
                    ps_id = p.pid
                    # print(ps_id)
                    # signal.alarm(5)
                    global tle
                    tle = False
                    result[counter] = str(p.stdout.readline().rstrip())
                    time_finish = False
                    print("answr : ", correct_op[counter], result[counter])
                    a = result[counter] + "b''"
                    temp = ""
                    result[counter] = result[counter][2:len(result[counter]) - 1]

                    # print(a)
                    # print(result[counter])
                    while not temp == "b''" and str(result[counter]).__len__() <= str(correct_op[counter]).__len__():
                        # result += "<br>"
                        temp = str(p.stdout.readline().rstrip())
                        if not temp == "b''":
                            temp = temp[2:len(temp) - 1]
                            result[counter] += temp
                        # print(result)

                    if str(correct_op[counter]) == result[counter]:
                        checker[counter] = True
                        marks += 2
                    else:
                        checker[counter] = False
                    counter += 1
                    os.killpg(os.getpgid(p.pid), signal.SIGTERM)
            # print(code)
            except:
                print('Error')
            score_object = Score.objects.get(user_f=current_user, question_f=current_question)
            if score_object.score < marks:
                current_user.money += (marks - score_object.score)
                score_object.score = marks
                score_object.save()

            # all_marks = list(jsonDec.decode(current_user.score))
            current_user.total_score = sum(Score.objects.filter(user_f=current_user).values_list('score', flat=True))
            current_user.save()
            return render(request, 'round2/question_details.html',
                          {'pegs_id': int("3"), 'error_msg': False, 'submitted': True, 'one': 50, 'two': 50,
                           'three': 100, 'four': 100, 'submitted_code': code, 'selected_question': current_question,
                           'user_id': user_id, 'checker': checker,
                           'remaining_time': current_user.end_time - time.time(),
                           'bought': True, 'question_id': question_id, 'question_score': score_object.score,
                           'money': current_user.money})
        else:
            print(subprocess.CalledProcessError)
            # print(compile_ouput)

            f = open('output.txt', 'w')
            f.write(compile_ouput)
            f.close()

            return render(request, 'round2/question_details.html',
                          {'pegs_id': int("3"), 'submitted': False, 'submitted_code': code,
                           'selected_question': current_question,
                           'user_id': user_id, 'checker': False,

round2/templates/round2/leaderboard.html
<html>
<head>
<style>
h1{text-align :center; color:#DDDDDD;}
table, th {
    border: 2px solid black;
    border-collapse: collapse;
	background-color: #777777;
}
td {
    border: 2px solid black;
    border-collapse: collapse;

}
th, td {
    padding: 5px;

}
th {
    text-align: left;
}
input[type="submit"]{
/* change these properties to whatever you want */
 width="50";
 height="0.5";
 padding: 6px 17px;

  font-size: 15px;
  text-align: center;
  cursor: pointer;
background-color: #6D6968;
color: #fff;
border-radius: 4px;
}
input[type="submit"]:hover {background-color: #D1D0DE;
border-radius:7px;
color: #2C3539;

}
</style>
</head>
<body bgcolor="#111111">
{% if leaderboard_clicked %}
<form action="{% url 'round2:question' user_id %}">
<input type="submit" name="back" id="back" value="Back">

    </form>
{% endif %}

<h1>LEADERBOARD</h1>
<table style="width:100% ">


  <tr  style="color:#FFFFFF">
	<th style="width:4%">RANK</th>
    <th>USERNAME</th>
    <th>COLLEGE</th>
    <th>SCORE</th>
  </tr>
    {% for user in all_user %}

    {% ifequal user_id user.pk %}

    <tr bgcolor="#BBBBBB" style="color:#000000">

    {% else %}
    <tr style="color:#FFFFFF" bgcolor="#444444">
    {% endifequal %}
        <td>{{forloop.counter}}</td>
        <td>{{user.login_name}}</td>
        <td>{{user.college_name1}}</td>
        <td>{{user.money}}</td>
    </tr>
    {% endfor %}
</table>

</body>
</html>

round2/templates/round2/login.html
<form action="{% url 'round2:create_user' %}" method="post">
    {% csrf_token %}
    <input type="text" id = "login_user_name" name ="login_user_name">
    <br>
    <input type="text" id = "login_password" name ="login_password">
    <br>
    <input type="submit" value="Login">

</form>

round2/templates/round2/questions_list.html
<style>
  div.fixed {
    position: fixed;
    margin-left:80%;
    margin-top:0%;

}
#code_editor1,#code_editor2,#code_editor3,#code_editor4,#code_editor5,#message_display{
	width: 75%;
	height:10%;
		border: 0.5px solid; border-color: #E4E4E4;
		background:#ffffff;
		  margin-left: 3%;  margin-bottom: 2%;
		padding: 1%;
		font-size:150%;
		font-family:Comic Sans MS;
	}
	body{
		background: #F3F3FF;
		          font-family: Arial, Helvetica, sans-serif;
	}

a:link {
    color: #0C090A;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: #33348e;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: #625D5D;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: #33348e;
    background-color: transparent;
    text-decoration: underline;
}



h1{
font-size:250%;

 font-family: "Comic Sans MS";

}
input[type="submit"],button{
/* change these properties to whatever you want */
 width="50";
 height="0.5";
 padding: 6px 17px;

  font-size: 15px;
  text-align: center;
  cursor: pointer;
background-color: #6D6968;
color: #fff;
border-radius: 4px;
}
input[type="submit"]:hover {background-color: #D1D0DE;
border-radius:7px;
color: #2C3539;

}
button:hover {background-color: #D1D0DE;
border-radius:7px;
color: #2C3539;

}
table,th,td{

border-collapse:collapse;
background-color:#ffffff;

 font-family:"Comic Sans MS";
}

</style>
<body >

    <h1 STYLE="margin-left:10%; ">Problem Statements </h1>
<div class="fixed">
    <label type="label" style= "background-color:black;color:#F3F3F3;font-family:courier;font-size:300%;margin-top:-15px;  " border="0"><b>
      <span id="time1"></span></b>

    </label>
</div>





<table style="margin-left:3%; width:75%; height:70%;">
    <tr  id="title" style=" font-weight: bold; font-size:145%;border:2px solid #E4E4E4;"><th>SOLVE PROBLEM</th> <th>YOUR SCORE</th><th> MAX SCORES </th></tr>
{% for question in all_questions %}

<tr id="{{forloop.counter}}" STYLE="border:1px solid #E4E4E4;"><td><a href="{% url 'round2:question_details' user_id question.pk  %}" style=" font-size: 150%; text-align:left; margin-left:10%;">{{question}}</a></td>
    {% for marks in all_marks %}
    {% ifequal forloop.parentloop.counter forloop.counter %}
    <td style="text-align:center;">{{marks}}</td><td style="text-align:center;">
    {% ifequal forloop.counter 1 %}
        {{one}}
     {% endifequal %}
     {% ifequal forloop.counter 2 %}
        {{two}}
     {% endifequal %}
     {% ifequal forloop.counter 3 %}
        {{three}}
     {% endifequal %}
        {% ifequal forloop.counter 4 %}
        {{four}}
     {% endifequal %}
        {% ifequal forloop.counter 5 %}
        {{five}}
     {% endifequal %}

    </td></tr>
    {% endifequal %}
    {% endfor %}
 {% endfor %}
</table>


<form action="{% url 'round2:leaderboard' user_id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="leader" id="leader" value="View Leaderboard" style="margin-left:70%;margin-top:3%;">

</form>
    <button onclick="prompt_user()" style="margin-left:75%;" >Finish</button>

<script>
    function prompt_user(){
    if (confirm('Are you sure you want to save this thing into the database?')) {
    window.location.replace(" {%url 'round2:leaderboard' user_id %}" );
} else {
    // Do nothing!
}
    }
</script>

</body>
<script type="text/javascript">

          function startTimer(duration, display)
          {
        var start = Date.now(),

        diff,
        minutes,
        seconds;

        function timer() {
        // get the number of seconds that have elapsed since
        // startTimer() was called
        diff = duration - (((Date.now() - start) / 1000) | 0);

        // does the same job as parseInt truncates the float
        hours = (diff / 3600) | 0;
        minutes = ((diff/60)%60) | 0;
        seconds = (diff % 60) | 0;
        hours = hours < 10 ? "0" + hours : hours;
        minutes = minutes < 10 ? "0" + minutes : minutes;
        seconds = seconds < 10 ? "0" + seconds : seconds;

        display.textContent =hours+ ":" + minutes + ":" + seconds;


        if (diff <= 0) {
            // add one second so that the count down starts at the full duration
            // example 05:00 not 04:59
           // start = Date.now() + 1000;
          // window.location.replace("http:/comp/leaderboard/" );
           window.location.replace(" {%url 'round2:leaderboard' user_id %}" );

        }

    };
    // we don't want to wait a full second before the timer starts
    timer();
    setInterval(timer, 1000);
}
window.onload = function ()
{
    var v = "{{remaining_time}}";

    display = document.querySelector('#time1');
    startTimer( v, display);
};

</script>


round2/templates/round2/select_questions.html
<!DOCTYPE html>
<html lang="en">
<style>

    body {
        background: #F3F3FF;
        font-family: Arial, Helvetica, sans-serif;
    }

    table, th, td {

        border-collapse: collapse;
        background-color: #ffffff;

        font-family: serif;
    }
</style>
<head>


</head>
<body>
<form action="{% url 'round2:leaderboard' user_id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="leader" id="leader" value="View Leaderboard" style="margin-left:70%;margin-top:3%;">

</form>
    <button onclick="prompt_user()" style="margin-left:75%;" >Finish</button>

{{ money }}
<!--ROUND 2-->
<h1 STYLE="margin-left:10%; ">Problem Statements </h1>
<div class="fixed">
    <label
            style="background-color:black;color:#F3F3F3;font-family:serif;font-size:300%;margin-top:-15px;  "
    ><b>
        <span id="time1"></span></b>

    </label>
</div>
<table style="margin-left:3%; width:75%; height:70%;">
    <tr id="title" style=" font-weight: bold; font-size:145%;border:2px solid #E4E4E4;">
        <th>Question No</th>
        <th>DIFFICULTY</th>
        <th>SOLVE PROBLEM</th>
        <th>STATUS</th>
        <th>COST</th>
        <th>MARKS<th>
    </tr>
    {% for question in question_list %}

        <tr id="{{ forloop.counter }}">
        <td>{{ forloop.counter }}</td>
        <td>{{ question.difficulty }}</td>
        <td><a href="{% url 'round2:question_details' user_id question.question.pk %}"
               style=" font-size: 150%; text-align:left; margin-left:10%;">{{ question.question.question_title }}</a>
        </td>
        <td>{{ question.status }}</td>
        <td>{{ question.cost }}</td>
        <td>{{ question.question_score }}</td>
    {% endfor %}

    </tr>
</table>
</body>

<script type="text/javascript">

    function startTimer(duration, display) {
        var start = Date.now(),

            diff,
            minutes,
            seconds;

        function timer() {
            // get the number of seconds that have elapsed since
            // startTimer() was called
            diff = duration - (((Date.now() - start) / 1000) | 0);

            // does the same job as parseInt truncates the float
            hours = (diff / 3600) | 0;
            minutes = ((diff / 60) % 60) | 0;
            seconds = (diff % 60) | 0;
            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = hours + ":" + minutes + ":" + seconds;


            if (diff <= 0) {
                // add one second so that the count down starts at the full duration
                // example 05:00 not 04:59
                // start = Date.now() + 1000;
                // window.location.replace("http:/comp/leaderboard/" );
                window.location.replace(" {%url 'round2:leaderboard' user_id %}");
            }

        };
        // we don't want to wait a full second before the timer starts
        timer();
        setInterval(timer, 1000);
    }

    window.onload = function () {
        var v = "{{remaining_time}}";

        display = document.querySelector('#time1');
        startTimer(v, display);
    };

</script>
</html>




round2/templates/round2/select_questions_new.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Select Questions | EarnCode</title>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static '/css/font.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <link rel="stylesheet"
          href="{% static '/css/jquery-ui.min.css' %}">
    <script src="{% static '/js/jquery-ui.min.js' %}"></script>

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">


    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <style>
        .leader {
            background: whitesmoke;
        }
    </style>
</head>
<body>
<br>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-2">

                <img alt="EarnCode"
                     src="{% static '/round2/images/ea.png' %}" width="100%">

            </div>
            <div class="col-md-4">
                <h2 style="margin-top: 60px;">Earn Code Round #2</h2>
            </div>
            <div class="col-md-2 col-md-offset-1">
                <div class="row"><h4 style="margin-top: 30px; margin-bottom: -5px;">WALLET BALANCE</h4></div>
                <div class="row text-center"><h2><span id="">&#8377; {{ money }}</span></h2></div>
            </div>
            <div class="col-md-2 col-md-offset-1 text-right">
                <div class="row"><h4 style="margin-top: 30px; margin-bottom: -5px;">TIME</h4></div>
                <div class="row"><h2><span id="time1">time</span></h2></div>
            </div>

        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li id="instruction_tab"><a onclick="showInstructions();">Instructions</a></li>
                    <li class="active" id="question_tab"><a onclick="showQuestions()">Question list</a></li>

                </ul>

                <form action="{% url 'round2:leaderboard' user_id %}" method="post" class="navbar-form navbar-right"
                      style="margin-bottom: -8px;margin-top: 1px;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default navbar-btn" id="leader" name="leader">View
                        Leaderboard
                    </button>
                    <button type="button" class="btn btn-default navbar-btn btn-danger" onclick="prompt_user()">
                        Finish
                    </button>

                </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


    <div class="row">


    </div>

    <br>
    <div class="row leader" id="question_list">
        <div class="table-responsive">
            <table class="table table-bordered white">
                <thead class="thead-inverse">
                <tr>
                    <th>Question No</th>
                    <th>Difficulty</th>
                    <th>Solve Problem</th>
                    <th>Status</th>
                    <th>Cost</th>
                    <th>Marks</th>
                </tr>
                </thead>
                <tbody id="table_body">
                {% for question in question_list %}

                    <tr id="{{ forloop.counter }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ question.difficulty }}</td>
                        <td><a href="{% url 'round2:question_details' user_id question.question.pk %}"
                               style=" font-size: 150%; text-align:left; margin-left:10%;">{{ question.question.question_title }}</a>
                        </td>
                        <td>{{ question.status }}</td>
                        <td>&#8377; {{ question.cost }}</td>
                        <td>{{ question.question_score }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
<div id="instruction" style="display: none;" class="container text-center">

    <div class="row">

        <div class="login-form col-md-6 col-md-offset-3">

            <ol>
                <p>
                <li> Second round consists of 4 problem statements which has 2 hours as the time limit.</li>
                <br>

                <li>This Round consists of 2 easy level questions, 2 medium level questions</li>
                <br>

                <li>Each easy level question is for 50 marks,Medium level question is for 100 marks
                </li>

                <br>
                <li>You are not suppose to press back and refresh buttons else you will be disqualified.</li>
                <br>


                </p>
            </ol>

        </div>
    </div>

</div>

</body>

<script type="text/javascript">

    function startTimer(duration, display) {
        var start = Date.now(),

            diff,
            minutes,
            seconds;

        function timer() {
            // get the number of seconds that have elapsed since
            // startTimer() was called
            diff = duration - (((Date.now() - start) / 1000) | 0);

            // does the same job as parseInt truncates the float
            hours = (diff / 3600) | 0;
            minutes = ((diff / 60) % 60) | 0;
            seconds = (diff % 60) | 0;
            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = hours + ":" + minutes + ":" + seconds;


            if (diff <= 0) {
                // add one second so that the count down starts at the full duration
                // example 05:00 not 04:59
                // start = Date.now() + 1000;
                // window.location.replace("http:/comp/leaderboard/" );
                window.location.replace(" {%url 'round2:leaderboard' user_id %}");
            }

        };
        // we don't want to wait a full second before the timer starts
        timer();
        setInterval(timer, 1000);
    }

    window.onload = function () {
        var v = "{{remaining_time}}";

        display = document.querySelector('#time1');
        startTimer(v, display);
    };

</script>
<script>
    function prompt_user() {
        if (confirm('Are you sure you want to save this thing into the database?')) {
            window.location.replace(" {%url 'round2:leaderboard' user_id %}");
        } else {
            // Do nothing!
        }
    }
</script>
<script>
    function showInstructions() {
        document.getElementById('question_list').style.display = "none";
        document.getElementById('question_tab').classList.remove('active');
        document.getElementById('instruction').style.display = "block";
        document.getElementById('instruction_tab').className += "active";

    }
</script>
<script>
    function showQuestions() {
        document.getElementById('instruction').style.display = "none";
        document.getElementById('instruction_tab').classList.remove('active');
        document.getElementById('question_list').style.display = "block";
        document.getElementById('question_tab').className += "active";

    }
</script>
</html>